name: Code Check

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "develop" ]

jobs:
  code-check:
    name: code-check
    runs-on: docker
    container:
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: https://github.com/astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff check
        run: |
          uv run ruff check .

#      # Only trigger the build workflow if this is a push to main branch and all checks pass
#      - name: Trigger build workflow
#        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && success() }}
#        run: |
#          curl -X POST \
#            -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
#            -H "Accept: application/json" \
#            -H "Content-Type: application/json" \
#            "${{ github.server_url }}/api/v1/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches" \
#            -d '{"ref":"main"}'