"""Initial migration

Revision ID: 0527919c56ac
Revises:
Create Date: 2025-07-04 15:09:55.892574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0527919c56ac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allowed_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_title", sa.String(length=255), nullable=True),
        sa.Column("allowed_by_admin_id", sa.BigInteger(), nullable=False),
        sa.Column("allowed_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
    )
    op.create_index(
        "idx_allowed_groups_active", "allowed_groups", ["is_active"], unique=False
    )
    op.create_index(
        "idx_allowed_groups_chat_id", "allowed_groups", ["chat_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.Column("image_description", sa.Text(), nullable=True),
        sa.Column("has_photo", sa.Boolean(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("is_forwarded", sa.Boolean(), nullable=True),
        sa.Column("forward_from_username", sa.String(length=255), nullable=True),
        sa.Column("forward_from", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    op.create_index(
        "idx_messages_chat_user_time",
        "messages",
        ["chat_id", "user_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_chat_user_time", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_allowed_groups_chat_id", table_name="allowed_groups")
    op.drop_index("idx_allowed_groups_active", table_name="allowed_groups")
    op.drop_table("allowed_groups")
    # ### end Alembic commands ###
