"""Add summary cache

Revision ID: d05d8abd2154
Revises: 0527919c56ac
Create Date: 2025-07-07 01:08:09.483555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d05d8abd2154"
down_revision: Union[str, Sequence[str], None] = "0527919c56ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunk_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.String(length=255), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("start_message_id", sa.BigInteger(), nullable=False),
        sa.Column("end_message_id", sa.BigInteger(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id"),
    )
    op.create_index(
        "idx_chunk_summaries_chat_id", "chunk_summaries", ["chat_id"], unique=False
    )
    op.create_index(
        "idx_chunk_summaries_range",
        "chunk_summaries",
        ["chat_id", "start_message_id", "end_message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_chunk_summaries_range", table_name="chunk_summaries")
    op.drop_index("idx_chunk_summaries_chat_id", table_name="chunk_summaries")
    op.drop_table("chunk_summaries")
    # ### end Alembic commands ###
