"""Remove unique constraint in Messages table

Revision ID: e8ce85b159dc
Revises: d05d8abd2154
Create Date: 2025-07-11 17:21:48.821872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ce85b159dc'
down_revision: Union[str, Sequence[str], None] = 'd05d8abd2154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_message_id_key'), 'messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('messages_message_id_key'), 'messages', ['message_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
